### ISSUE TITLE
Chooose Format

### ISSUE THREAD

**Issue by kolbdog3333** [vaaski/go-yt-dlp#2]
HI i am just trying out your software for the wrapper for yt-dlp and like it so far but be nice if you could select your own format instead of only choosing quick(mp4) and mp4. since may not always want the highest quality video or the default fast qualtiy. Thanks in advnace maybe type in your own format like 368+140 when you go to the format selection go to custom format or something like that.

**Comment by vaaski** [comment]
Hey thanks for trying it out. Custom format sounds like a good idea, I'll look into it!

**Comment by vaaski** [comment]
You can now select the `custom` format and enter something to be passed into [yt-dlp's `-f` format flag](https://github.com/yt-dlp/yt-dlp#format-selection).

**Comment by kolbdog3333** [comment]
Just tried it but it crashes moment push enter

**Comment by vaaski** [comment]
Oh, that might be related to #3.
Can you try with the newest commit? If it still doesn't work, can you please provide the link and format you used?
